# Site settings
title: Dr. Vikas Gupta
email: vikasjjm143@gmail.com
url: https://minetestaccount.github.io/drvikasgupta/
description: "Orthopedic surgeon - Treatment from head to toe"
keywords: "Doctor, Orthopedic, surgeon, Ambikapur"
skills: "Orthopedic surgeon - Treatment from head to toe"
meta_author: Gupta Dr.Vikas

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Vikas Gupta
  location: Location
  social: Around the Web
  credits: Working Hour

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: share-alt
#    url: https://minetestaccount.github.io/drvikasgupta/
  - title: facebook
    url: https://www.facebook.com/people/Dr-Vikas-Gupta-Orthopaedic-Surgeon/100067774251106/
#  - title: phone-square
#    url: tel:+917996247883
  - title: google-plus
    url: mailto:vikasjjm143@gmail.com
  - title: whatsapp
    url: http://wa.me/+917996247883

# Postal address (add as many lines as necessary)
address:
  - line: Govt. Hospital, Surajpur (C.G.)
  - line: LifeLine Hospital, Ambikapur (C.G.)

# Credits content
credits: '09:00 AM TO 05:00 PM IST <br> Mobile: +917996247883'


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
